#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint
npm test

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "master" ]; then
  echo "You can't push directly to master branch"
  exit 1
fi
if [ "$branch" = "main" ]; then
  echo "You can't push directly to master branch"
  exit 1
fi